apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.cordapp.name }}
  labels:
    app: {{ template "cordapp.name" . }}
    chart: {{ template "bank-operations.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  loadBalancerIP: "{{ .Values.config.nodeLoadBalancerIP }}"
  type: LoadBalancer
  selector:
    app: {{ template "cordapp.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: p2p
    protocol: TCP
    port: {{ .Values.corda.node.conf.p2pPort }}
    targetPort: {{ .Values.corda.node.conf.p2pPort }}
  - name: rpc
    protocol: TCP
    port: {{ .Values.corda.node.conf.rpc.port }}
    targetPort: {{ .Values.corda.node.conf.rpc.port }}
{{- if .Values.corda.node.conf.ssh.enabled }}
  - name: ssh
    protocol: TCP
    port: {{ .Values.corda.node.conf.ssh.sshdPort }}
    targetPort: {{ .Values.corda.node.conf.ssh.sshdPort }}
{{- end }}